language: node_js
node_js:
- '0.12'
before_install:
  - git config --global user.email "dev@bitpay.com"
  - git config --global user.name "BitPay, Inc."
  - sudo apt-get install libboost-all-dev
after_script:
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
